// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Entities;

namespace WebApi.Migrations
{
    [DbContext(typeof(StudentsContext))]
    [Migration("20220218045949_MyFirstMigration1")]
    partial class MyFirstMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.HasSequence<int>("id", "dbo");

            modelBuilder.HasSequence<int>("rollno", "dbo");

            modelBuilder.Entity("WebApi.Entities.Mark", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.Order_seq");

                    b.Property<int>("mark1Value")
                        .HasColumnType("integer");

                    b.Property<int>("mark2Value")
                        .HasColumnType("integer");

                    b.Property<int>("mark3Value")
                        .HasColumnType("integer");

                    b.Property<int>("rollno")
                        .HasColumnType("integer");

                    b.Property<int>("totalmarks")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("WebApi.Entities.Student", b =>
                {
                    b.Property<int?>("rollno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.Order_seq");

                    b.Property<string>("firstname")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("lastname")
                        .HasColumnType("text");

                    b.Property<string>("phoneno")
                        .HasColumnType("text");

                    b.HasKey("rollno");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
